 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/timeslots", type: :request do
  # Timeslot. As you add validations to Timeslot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Timeslot.create! valid_attributes
      get timeslots_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      timeslot = Timeslot.create! valid_attributes
      get timeslot_url(timeslot)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_timeslot_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      timeslot = Timeslot.create! valid_attributes
      get edit_timeslot_url(timeslot)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Timeslot" do
        expect {
          post timeslots_url, params: { timeslot: valid_attributes }
        }.to change(Timeslot, :count).by(1)
      end

      it "redirects to the created timeslot" do
        post timeslots_url, params: { timeslot: valid_attributes }
        expect(response).to redirect_to(timeslot_url(Timeslot.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Timeslot" do
        expect {
          post timeslots_url, params: { timeslot: invalid_attributes }
        }.to change(Timeslot, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post timeslots_url, params: { timeslot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested timeslot" do
        timeslot = Timeslot.create! valid_attributes
        patch timeslot_url(timeslot), params: { timeslot: new_attributes }
        timeslot.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the timeslot" do
        timeslot = Timeslot.create! valid_attributes
        patch timeslot_url(timeslot), params: { timeslot: new_attributes }
        timeslot.reload
        expect(response).to redirect_to(timeslot_url(timeslot))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        timeslot = Timeslot.create! valid_attributes
        patch timeslot_url(timeslot), params: { timeslot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested timeslot" do
      timeslot = Timeslot.create! valid_attributes
      expect {
        delete timeslot_url(timeslot)
      }.to change(Timeslot, :count).by(-1)
    end

    it "redirects to the timeslots list" do
      timeslot = Timeslot.create! valid_attributes
      delete timeslot_url(timeslot)
      expect(response).to redirect_to(timeslots_url)
    end
  end
end
